### ISSUE TITLE
If the slogan is too long, it will not adapt itself on the small screen device.

### ISSUE THREAD

**Issue by cuteist** [cntrump/hugo-notepadium#10]
Hugo Version:  0.62
Build Command: hugo server -D
For example:
![example.png](https://i.loli.net/2020/01/02/Y8EQCPAibldrF5k.png)

**Comment by cntrump** [comment]
Thanks, got it.
Working on it ...

**Comment by cntrump** [comment]
Fixed, try the latest code please.

**Comment by cuteist** [comment]
> Fixed, try the latest code please.

Thanks.It's perfect now
