### ISSUE TITLE
Blank blockquote appears after adding script

### ISSUE THREAD

**Issue by Aizera** [cntrump/hugo-notepadium#102]
Hugo Version:  0.68.3
Build Command: hugo --gc --minify

Hello,
I added an utterances script today to my blog post, and a blank blockquote appeared between the comments and the tags. Is it removable?
This is what I was expecting it to look like:
![image](https://user-images.githubusercontent.com/33512904/92313158-29d50c00-ef7d-11ea-8755-34ce24126d56.png)  

This is what it looks like right now:
![image](https://user-images.githubusercontent.com/33512904/92313164-335e7400-ef7d-11ea-9f6f-0ed1a160d587.png)  

This is the post in question:
https://aizera.page/post/welcome-to-riot-support-how-can-we-help/

Much thanks!

**Comment by cntrump** [comment]
Could you post the raw markdown for testing ?

**Comment by Aizera** [comment]
+++
date = 2020-04-15T08:52:36Z
tags = ["leagueoflegends"]
title = "Welcome to Riot Support. How can we help?"

+++
Your opinion is important to us. Please hold while we connect you to an agent.

<script src="https://utteranc.es/client.js"
        repo="Aizera/hugo-notepadium"
        issue-term="pathname"
        label="Blog Comments"
        theme="photon-dark"
        crossorigin="anonymous"
        async>
</script>

**Comment by Aizera** [comment]
posted above is the markdown file in question, thank you! Also I was hoping to enable comments for future posts, so I hope it works with snippet injection too (or a different method if I learned how).

**Comment by Aizera** [comment]
I decided to add the script to the article files comments sessions and it seems to work (albeit differently) now. Thank you again

**Comment by cntrump** [comment]
> +++
> date = 2020-04-15T08:52:36Z
> tags = ["leagueoflegends"]
> title = "Welcome to Riot Support. How can we help?"
> 
> +++
> Your opinion is important to us. Please hold while we connect you to an agent.
> 
> <script src="https://utteranc.es/client.js" repo="Aizera/hugo-notepadium" issue-term="pathname" label="Blog Comments" theme="photon-dark" crossorigin="anonymous" async> </script>

Thanks.
I tested with latest code and can't reproduce this problem.
You can try wrap raw HTML with shortcode `{{<raw>}}` in your md file.

```html
{{<raw>}}
<script src="https://utteranc.es/client.js" repo="Aizera/hugo-notepadium" issue-term="pathname" label="Blog Comments" theme="photon-dark" crossorigin="anonymous" async> </script>
{{</raw>}}
```
