### ISSUE TITLE
`<li>` margins don't look natural

### ISSUE THREAD

**Issue by shanehou** [cntrump/hugo-notepadium#118]
Hugo Version:  v0.83.1
Build Command: `hugo server -D`

The `<li>` style is a bit strange: when `li+li` has a 20px margin-top, why does the first child has 0px margin-top? The nested `<li>` would look like this:

![image](https://user-images.githubusercontent.com/863379/129470134-983867e1-1a1a-44ae-ab0a-7a43b3f98439.png)

See? When nested, the margin is not consistent. The better style in my opinion should be:

![image](https://user-images.githubusercontent.com/863379/129470159-2ecda3be-db20-4494-bea3-c2354e4fdfc7.png)

Or:

![image](https://user-images.githubusercontent.com/863379/129470174-950bb435-c201-4d0d-9f44-23296c7308f4.png)

**Comment by cntrump** [comment]
Fixed: https://github.com/cntrump/hugo-notepadium/pull/120
