### ISSUE TITLE
Enable configurable date format

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#14]
Right now, it's hardcoded ISO style. 

https://github.com/cntrump/hugo-notepadium/blob/3b406de2f4809fea3541a2a3d4ef873728cab959/layouts/_default/single.html#L7

It would be nice if there were a way to configure this from params without having to override the partial.

**Comment by cntrump** [comment]
OK, a global var will be added:

```toml
[params]
dateFormat = "2006-01-02"
```

working on it...

**Comment by cntrump** [comment]
Done.
