### ISSUE TITLE
How to remove "Powered by Hugo and the Notepadium" footer credits?

### ISSUE THREAD

**Issue by sps45** [cntrump/hugo-notepadium#15]
Hugo Version:  v0.62.1-A1518704
Build Command: hugo

Hey how could I go about doing this? Love the theme, but I'm no web dev - I couldn't figure this one out. Thanks

**Comment by cntrump** [comment]
You can overide footer:

In your site root, create an empty `copyright.html` at `/layouts/partials/`
```
.
└── layouts
    └── partials
        └── copyright.html
```

**Comment by cntrump** [comment]
overide `copyright.html`

```html
{{- $copyright := . -}}
<p>{{- $copyright -}}</p>
```

**Comment by sps45** [comment]
I appreciate the reply - However, I want to keep the copyright section and remove the "Powered by Hugo and the Notepadium" bit. (I use the copyright section for my email address).. Is this possible? Thanks mate

**Comment by cntrump** [comment]
Try this:

`copyright.html`, add a new line.
```html
{{- $copyright := . -}}
<p>{{- $copyright -}}</p>
<p><a href="mailto:XXX@me.com">mail to me</a></p>
```
