### ISSUE TITLE
Suggestion: more contrast in fonts

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#18]
Currently, I think the dark and light themes fonts don't have quite enough contrast:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/13618205/71704774-928a3a00-2d99-11ea-9124-84811f057e33.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/13618205/71704780-9ddd6580-2d99-11ea-8c88-1e9bec3da4cf.png">

---

I suggest changing the light font to `rgba(0, 0, 0, 0.8)` and the  dark font to `rgba(255, 255, 255, 0.8)`:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/13618205/71704821-cb2a1380-2d99-11ea-96d4-18a04ecc3706.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/13618205/71704841-e006a700-2d99-11ea-8425-a843b70495f1.png">

**Comment by layoutboy** [comment]
Now supported custom CSS, let users define their own styles?

**Comment by cntrump** [comment]
Now supported custom CSS, let users define their own styles?

**Comment by layoutboy** [comment]
That's what I think, We can provide some CSS as custom style.

**Comment by cntrump** [comment]
That's what I think, We can provide some CSS as custom style.

**Comment by Benjamin-Lee** [comment]
I have defined my own style (how I generated the screenshots) but there are two issues:

1. As the template evolves, keeping track of all the classes is a hassle, e.g.:
```css
.note-content,
.site-name,
.date,
.article-header,
.note-title,
.note-date, <-- for example, the class is now date, not note-date
.markdown-body,
.markdown-body h1,
.markdown-body h2,
.markdown-body h3,
.markdown-body h4,
.markdown-body h5
```

2. I'm suggesting changing the default to enhance accessibility out of consideration for users with vision challenges since most users probably won't change the color from the default.

Either way, I suggest using a CSS var for font color to make it easier to change.

**Comment by cntrump** [comment]
OK, I got your point.
You can make a PR for me 😁

**Comment by cntrump** [comment]
I reorganize CSS classes

And the class name won't be changed.

You can custom color with light and dark

light

```css
body { color: teal; }

.article.markdown-body,
.article.markdown-body h1,
.article.markdown-body h2,
.article.markdown-body h3,
.article.markdown-body h4,
.article.markdown-body h5,
.article.markdown-body h6 { color: brown; }

.site.name { color: tomato; }

.nav.item { color: royalblue; }

.site.slogan .title { color: sandybrown; }

.article.title { color: slategray; }

.article.date { color: steelblue; }

.article.tag { color: violet; }

.article.category { color: teal; }

.article.navigation .link { color: skyblue; }

.note.title { color: sienna; }

.note.date { color: thistle; }

.note.content { color: wheat; }

.note.tag { color: yellow; }

.note.category { color: seagreen; }
```

dark
```css
@media (prefers-color-scheme: dark) {

body { color: teal; }

.article.markdown-body,
.article.markdown-body h1,
.article.markdown-body h2,
.article.markdown-body h3,
.article.markdown-body h4,
.article.markdown-body h5,
.article.markdown-body h6 { color: brown; }

.site.name { color: tomato; }

.nav.item { color: royalblue; }

.site.slogan .title { color: sandybrown; }

.article.title { color: slategray; }

.article.date { color: steelblue; }

.article.tag { color: violet; }

.article.category { color: teal; }

.article.navigation .link { color: skyblue; }

.note.title { color: sienna; }

.note.date { color: thistle; }

.note.content { color: wheat; }

.note.tag { color: yellow; }

.note.category { color: seagreen; }

}
```

**Comment by cntrump** [comment]
[exampleSite](https://exampleSite.lvv.me) updated.

**Comment by cntrump** [comment]
https://github.com/cntrump/hugo-notepadium-style
