### ISSUE TITLE
How to remove Next Article recommendation at the bottom of blog posts?

### ISSUE THREAD

**Issue by sps45** [cntrump/hugo-notepadium#20]
Hugo Version:  Hugo Static Site Generator v0.62.1-A1518704
Build Command: hugo

One last question! At the bottom of my blog posts, I get a link to the previous article. Is there a way to remove this? I've attached a photo of how this link appears.  
  
![link](https://user-images.githubusercontent.com/9097393/71741464-fb6ec200-2e2c-11ea-8ab8-bb62737e38b5.jpg)

Also, is there any documentation on overriding UI elements from within hugo (specific to this theme?)  
  
Thanks!

**Comment by cntrump** [comment]
Update latest code, now supported.

Create an empty partial on your site root: `./layouts/partials/article-bottom-navigation.html`

**Comment by sps45** [comment]
Thanks for the help. I don’t want to create another issue for this, but could you possibly add support for favicons? Ive been trying to figure out how to do this all day.  
  
Initially, I tried creating an empty “header.html” file in the ‘partials’ folder, but that didn’t work.  I added this code to the 'header.html' file, in hopes that the favicon would be added to the website, but it overwrote the entire header.

https://pastebin.com/raw/xwHHW2ke
 
As you can see, I the filenames for the favicons are files in my websites root. Was I on the right track?
  
 I appreciate your hard work. Thanks so much!  
  
EDIT: The code blocks aren't working for some reason. Added a pastebin link

**Comment by cntrump** [comment]
copy favicon.ico to `./static/favicon.ico`

**Comment by cntrump** [comment]
`./static/` is you website root

**Comment by cntrump** [comment]
any files in `./static/*` will be copy to website root.

**Comment by sps45** [comment]
This worked! Thanks!!!
