### ISSUE TITLE
Add support for "Last Updated" via git info

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#22]
It would be really nice to have a "last updated" option for pages derived from `.Lastmod` when using `--enableGitInfo`.

**Comment by cntrump** [comment]
Like below ?

`Dec 28, 2019 • edited Dec 29, 2019`

updated:  https://github.com/cntrump/hugo-notepadium/commit/78abdd2351fdad651b93e604451158b2cc5cae75

**Comment by cntrump** [comment]
Supported in v2.1.0 

https://github.com/cntrump/hugo-notepadium/releases/tag/v2.1.0

**Comment by yudapedia** [comment]
How to implement this on posts other than changing `enableGitInfo = true`?
