### ISSUE TITLE
Add support for SASS/SCSS in custom styles

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#24]
Hugo [already supports this](https://gohugo.io/hugo-pipes/scss-sass/), but I get the following error:

`"themes/hugo-notepadium/layouts/partials/custom-css.html:8:50": execute of template failed: template: partials/custom-css.html:8:50: executing "partials/custom-css.html" at <resources.Concat>: error calling Concat: resources in Concat must be of the same Media Type, got "text/x-sass" and "text/css"
`

**Comment by cntrump** [comment]
Got it

**Comment by cntrump** [comment]
Updated, build SASS/SCSS while filename has suffix `.sass` or `.scss`.

**Comment by Benjamin-Lee** [comment]
Thanks!
