### ISSUE TITLE
[How to]修改代码syntax和logo后生成出错

### ISSUE THREAD

**Issue by TrendingTechnology** [cntrump/hugo-notepadium#26]
你好，我从官方github库里下载了模板上传，并通过netlify生成，修改代码syntax和logo，生成出错，还有想请教下，logo和favicon应该上传到哪个目录对应网站目录呢？

7:58:15 PM: ERROR 2020/01/06 11:58:15 render of "section" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:20:4: executing "partials/head.html" at <partial "style.html" .>: error calling partial: "/opt/build/repo/themes/hugo-notepadium/layouts/partials/style.html:49:76": execute of template failed: template: partials/style.html:49:76: executing "partials/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
7:58:15 PM: ERROR 2020/01/06 11:58:15 render of "taxonomy" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:20:4: executing "partials/head.html" at <partial "style.html" .>: error calling partial: "/opt/build/repo/themes/hugo-notepadium/layouts/partials/style.html:49:76": execute of template failed: template: partials/style.html:49:76: executing "partials/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
7:58:15 PM: ERROR 2020/01/06 11:58:15 render of "taxonomy" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:20:4: executing "partials/head.html" at <partial "style.html" .>: error calling partial: "/opt/build/repo/themes/hugo-notepadium/layouts/partials/style.html:49:76": execute of template failed: template: partials/style.html:49:76: executing "partials/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
7:58:15 PM: ERROR 2020/01/06 11:58:15 render of "taxonomyTerm" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:20:4: executing "partials/head.html" at <partial "style.html" .>: error calling partial: "/opt/build/repo/themes/hugo-notepadium/layouts/partials/style.html:49:76": execute of template failed: template: partials/style.html:49:76: executing "partials/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
7:58:15 PM: Total in 49 ms
7:58:15 PM: Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:20:4: executing "partials/head.html" at <partial "style.html" .>: error calling partial: "/opt/build/repo/themes/hugo-notepadium/layouts/partials/style.html:49:76": execute of template failed: template: partials/style.html:49:76: executing "partials/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
7:58:15 PM: Skipping functions preparation step: no functions directory set
7:58:15 PM: Caching artifacts
7:58:15 PM: failed during stage 'building site': Build script returned non-zero exit code: 255
7:58:15 PM: Started saving pip cache
7:58:15 PM: Finished saving pip cache
7:58:15 PM: Started saving emacs cask dependencies

**Comment by cntrump** [comment]
在你的 hugo 目录下创建 `./static/` 目录
 `favicon.ico` 放在里面：`./static/favicon.ico`
logo 也可以放进去，放在子目录也可以：`./static/img/logo.png`

config.toml 里面配置路径：

```toml
[params]
logo = "/img/logo.png" 
```

**Comment by cntrump** [comment]
`./static/` 里面的目录结构会被原样拷贝到网站根目录里，而且会覆盖主题中的同名文件。

**Comment by cntrump** [comment]
如果是自定义的 CSS 和 JS，文件只能放在 Hugo 根目录 `./assets/` 里：

比如：`./assets/css/fonts.css`

配置文件里的路径是相对于 `./assets/` 的：

```toml
[params.assets]
css = ["css/fonts.css"]
```

**Comment by cntrump** [comment]
根据你的信息，报错应该是找不到对应代码主题。
这个是bug，我做一下容错。

**Comment by TrendingTechnology** [comment]
非常感谢，上传图片路径对了之后，修改logo配置成功。

**Comment by cntrump** [comment]
语法高亮主题路径不存在会报错的问题，已经修复了。
可以保证构建成功，但是语法高亮会失效。

**Comment by cntrump** [comment]
这里的语法高亮配置
```toml
[params.syntax]
theme = "xcode"
darkTheme = "xcode-dark"
```

需要主题目录里 `./assets/css/` 对应存在对应的文件，要不就没有效果。
需要自己手动看一下都有哪些主题可以选。
