### ISSUE TITLE
Author blurb at end of article?

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#28]
One thing I noticed when reading [this](https://www.justindfuller.com/2020/01/go-things-i-love-channels-and-goroutines/) blog post was the little picture with the description of the author at the end. It might be a good idea to add something like this to the site. I tried my hand at making a partial but got stuck trying to make it responsive. Do you have any ideas?

**Comment by Benjamin-Lee** [comment]
Sorry, I realize the blurb is only at the bottom of that link on mobile. [Here's](https://leowid.com/flying/) a better example

**Comment by cntrump** [comment]
Don't know what the user wants to show at bottom, personal profile or Ads ?

I think we Don't need to think so much about advanced users.

Just add an empty partial, they can do anything(read site config or page params) and show any thing.
