### ISSUE TITLE
[BUG] Formula with number

### ISSUE THREAD

**Issue by xueqian-chen** [cntrump/hugo-notepadium#29]
Hugo Version:  0.62.1-A1518704
Build Command: hugo --minify

作者你好，当公式带编号的时候，显示会出问题，如下图：
![公式](https://github.com/xueqian-chen/CompareTextFiles/blob/master/%E5%85%AC%E5%BC%8F.png)
我在火狐、chrome、Edge、IE浏览器都试过了，都有这个问题。

此外，行间是左对齐的，请问能提供使公式居中的设置吗？

**Comment by cntrump** [comment]
提供一下测试的 markdown，我测试好像布局正常：

```md
1.1 $$ \varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887… $$

2.1 $$ \varphi = 1+\frac{1} {1+\frac{1} {1+\frac{1} {1+\cdots} } } $$
```

可能某些场景下有问题。

**Comment by xueqian-chen** [comment]
> 
> 
> 提供一下测试的 markdown，我测试好像布局正常：
> 
> ```lisp
> 1.1 $$ \varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887… $$
> 
> 2.1 $$ \varphi = 1+\frac{1} {1+\frac{1} {1+\frac{1} {1+\cdots} } } $$
> ```
> 
> 可能某些场景下有问题。

作者回复好迅速，十分感谢！

**Comment by cntrump** [comment]
居中的问题我提交了一个更新，更新后试一下。

**Comment by xueqian-chen** [comment]
> 
> 
> 提供一下测试的 markdown，我测试好像布局正常：
> 
> ```lisp
> 1.1 $$ \varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887… $$
> 
> 2.1 $$ \varphi = 1+\frac{1} {1+\frac{1} {1+\frac{1} {1+\cdots} } } $$
> ```
> 
> 可能某些场景下有问题。

作者回复好迅速，十分感谢！

> 
> 
> 居中的问题我提交了一个更新，更新后试一下。

好的，感谢作者
