### ISSUE TITLE
root _index.md ignored

### ISSUE THREAD

**Issue by gatto** [cntrump/hugo-notepadium#32]
The theme's not including the custom contents of a root content/_index.md file. It's just ignoring it altogether.

(usual disclaimer: I might be wrong myself)

**Comment by cntrump** [comment]
`section` template is missing.
I added one, pull latest code and try again~

**Comment by gatto** [comment]
Hum, doesn't work for me.
The problem is that on my homepage (www.example.org/index.html) the content of /content/_index.md is not displayed.

**Comment by cntrump** [comment]
Got it.

Added `homepage-body.html` partial for that.

**Comment by gatto** [comment]
Works now 😀
