### ISSUE TITLE
support for favicon

### ISSUE THREAD

**Issue by JayFarei** [cntrump/hugo-notepadium#33]
I have added to the partials folder a new file - `favicon.html` - containing the html output of https://realfavicongenerator.net/?cse#.Xh4kaS2ca-Z // 

once that is done - favicon.html will look something like:
```
{{- $favicon := . -}}
<link rel=....
```

then added the favicon package from the generator to the static folder, in my case I did: 
```
.
└── static
    └── favicon
        └── files
```

then I added `{{- partial "favicon.html" . -}}` to `head.html` et voila'

worth adding it to the template? (also not sure my implementation is the best)

Thanks!

**Comment by cntrump** [comment]
Nice suggestion!
Added `head-extra.html` partial for custom.

**Comment by cntrump** [comment]
https://github.com/cntrump/hugo-notepadium/issues/34
