### ISSUE TITLE
[HOW TO] add favicon for all platforms & all browsers

### ISSUE THREAD

**Issue by cntrump** [cntrump/hugo-notepadium#34]
Idea from [@JayFarei](https://github.com/JayFarei)

Generate favicon:
https://realfavicongenerator.net

Create an user-side partial `head-extra.html`

```
./layouts/partials/head-extra.html
```

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#00a300">
<meta name="theme-color" content="#ffffff">
```

**Comment by RobinZenXD** [comment]
谢谢，thank you

**Comment by wglane** [comment]
I'm a little new to Hugo. Could you tell me where the `favicon-32x32.png` etc. are supposed to go? For example, do they go in the `static` folder?

**Comment by 1hiking** [comment]
> 
> 
> I'm a little new to Hugo. Could you tell me where the `favicon-32x32.png` etc. are supposed to go? For example, do they go in the `static` folder?

Not the appropiate place to discuss this neither in time... but for anyone who might come across this question... it's in the root folder of static.
