### ISSUE TITLE
tags 可以重命名或者支持i18n吗？

### ISSUE THREAD

**Issue by Alwayswithme** [cntrump/hugo-notepadium#35]
Hugo Version:  v0.62.2/extended darwin/amd64 

打开 https://lvv.me/tags/ 的时候，没找到 `Tags` 从哪里取值的。

```html
<section class="article header"><h1>Tags</h1></section>
```

**Comment by cntrump** [comment]
建议不错，可以提个pr，取值的地方是header

**Comment by Alwayswithme** [comment]
没找到🤣，还不是很懂hugo

最后通过 content/tags/_index.md 修改的

**Comment by cntrump** [comment]
> 没找到🤣，还不是很懂hugo
> 
> 最后通过 content/tags/_index.md 修改的

加上了，位置后来调整过，我自己都忘了。。
更新一下就可以。
