### ISSUE TITLE
无法使用disqus

### ISSUE THREAD

**Issue by qianmianyao** [cntrump/hugo-notepadium#37]
设置好disqusShortname还是没有评论框

**Comment by qianmianyao** [comment]
我是用hugo来写博客，用nginx来作为server服务器的，我在主题的disqus那个字段填写了我的name，但是没有作用。

**Comment by cntrump** [comment]
不是写 disqus 用户名，是 site name，参考一下：https://lvv.me/posts/2019/12/10_hugo_disqus/

**Comment by cntrump** [comment]
明白了，可能是没有全局开启。需要配置：

```toml
[params.comments]
enable = true  # En/Disable comments globally
```

**Comment by cntrump** [comment]
单篇文章开启或关闭，在头部设置 `comments = true/false`

**Comment by qianmianyao** [comment]
我填的是website name，设置如下
![0E2D44E1-4C7F-42B1-A6D4-61019A5FF4B6](https://user-images.githubusercontent.com/32097980/72861107-e2f31880-3d03-11ea-8514-037868d3063e.jpeg)
![EE5E794F-7A8D-4265-93C6-43E63C3C1277](https://user-images.githubusercontent.com/32097980/72861108-e2f31880-3d03-11ea-91d4-fee727ffb80d.jpeg)
![47951E17-84C1-4EB3-8E35-41BFBE8E0897](https://user-images.githubusercontent.com/32097980/72861127-ef777100-3d03-11ea-8d05-7d6a05cba2b7.jpeg)

我的站点https://netmao.club

**Comment by cntrump** [comment]
文章头部的 comments 是不是设置为 false 了，它会覆盖全局设置。

**Comment by qianmianyao** [comment]
![B7637D84-3E28-47C8-97AA-DA1C7D9E34F7](https://user-images.githubusercontent.com/32097980/72861700-a6282100-3d05-11ea-80f7-fc652c803e4a.jpeg)
我没有打开这个设置项啊，还是说全局打开后，文章还是默认关闭的？

**Comment by cntrump** [comment]
全局开启后，文章如果没有设置 comments ，就是全局设置。文章设置了 comments ，就覆盖全局的。
我这测试符合预期，你用的是 toml 格式还是 yml 格式的 config ？

**Comment by qianmianyao** [comment]
toml格式的

**Comment by qianmianyao** [comment]
在博客根目录的config.toml加上comments = true也还是不行

**Comment by cntrump** [comment]
> 在博客根目录的config.toml加上comments = true也还是不行

加这个没有用，没有读这个变量。我再看一下逻辑。或者你先改一下模版里的逻辑，先能用上：

```diff
diff --git a/layouts/partials/article-comments.html b/layouts/partials/article-comments.html
index 8507a91fd4926ecc20fadf921f8b00fd25ad2d2e..69afc87c0fb0ffd5a1ea1adc0f911fd33fdcafef 100644
--- a/layouts/partials/article-comments.html
+++ b/layouts/partials/article-comments.html
@@ -1,5 +1,5 @@
 {{- if gt (len site.DisqusShortname) 0 -}}
-    {{- if or (eq .Params.comments true) (and (ne .Params.comments false) (eq site.Params.comments.enable true)) -}}
+    {{- if eq site.Params.comments.enable true -}}
         <section class="article discussion">
             {{- template "_internal/disqus.html" . -}}
         </section>
```

这样就是全局开或者关评论，去掉了单篇文章评论的逻辑。

**Comment by qianmianyao** [comment]
还是有问题，我换方案了，换成了国内的一个评论模块，https://valine.js.org/
博客：https://netmao.club

**Comment by cntrump** [comment]
> 还是有问题，我换方案了，换成了国内的一个评论模块，https://valine.js.org/
> 博客：https://netmao.club

Disqus 需要科学上网，国内网络是加载不了的，我之前以为你是说的模版里的Disqus模块没有正确嵌入

**Comment by qianmianyao** [comment]
我知道，翻墙后依然加载不出来

**Comment by cntrump** [comment]
嵌入评论模块的逻辑有调整吗？如果没有的话，说明逻辑没有问题，我这测试重现不了，Hugo 0.62

**Comment by DarkKowalski** [comment]
> 设置好disqusShortname还是没有评论框

可以提供完整的 config.toml（可以改掉 PII 之类的信息、使用 placeholder） 和 hugo 以及 golang 等基本 runtime 版本信息吗。

**Comment by heiybb** [comment]
> 我知道，翻墙后依然加载不出来


> 嵌入评论模块的逻辑有调整吗？如果没有的话，说明逻辑没有问题，我这测试重现不了，Hugo 0.62

我这里复现成功
Hugo v0.68.3/extended windows/amd64
## Fail
当config.toml内加入了
```
[permalinks]
    post = "/:slug"
```
![image](https://user-images.githubusercontent.com/6506815/78969332-0df24900-7b4a-11ea-8d55-e1bfd24c8c11.png)

时必定复现成功(Disqus模块无法正确嵌入
![image](https://user-images.githubusercontent.com/6506815/78969201-c4096300-7b49-11ea-87b8-7e36c8a6205a.png)

## Success
删除这个rule后重新生成则能正常加载

![image](https://user-images.githubusercontent.com/6506815/78969092-84db1200-7b49-11ea-94f5-8fd54631bfb9.png)

## Fix
后怀疑于这个rule的位置有关，将这条rule移动至config.toml最底部位置时，rule生效，同时disqus也能正常加载，见下图
![image](https://user-images.githubusercontent.com/6506815/78969517-74776700-7b4a-11ea-9239-0fd021af6a44.png)

p.s. 刚来到Hugo阵营，可能文档还没看全，有问题的地方欢迎指出

**Comment by DarkKowalski** [comment]
You should check out the official documentation of toml-lang to understand the way hash table works, instead of blaming hugo or this theme, be advised there's "_Under that, and until the next table or EOF are the key/values of that table_". https://github.com/toml-lang/toml#table

**Comment by heiybb** [comment]
I am not blaming someone or saying that it is anyone's fault, I am providing a comparison to help him/her if s/he mis-configed the config file like what I did before, and I did emphasized that I was new here and haven't fully gone through the documents.
Thanks for the link anyway, it perfectly explains the mistake.

**Comment by cntrump** [comment]
> ## Fail
> 当config.toml内加入了
> 
> ```
> [permalinks]
>     post = "/:slug"
> ```

如果是这样就好解释了，解析器会认为以下的配置是属于 `[permalinks ]` 的 Key：

```toml
[permalinks]
    post = "/:slug"
enableRobotsTXT = true
summaryLength = 70

# disqus
disqusShortname = "XXXX"
```

正确写法是把 `[XXX]`放在全局配置之后：

```toml
enableRobotsTXT = true
summaryLength = 70

# disqus
disqusShortname = "XXXX"

[permalinks]
    post = "/:slug"
```
