### ISSUE TITLE
Improvement for internationalisation

### ISSUE THREAD

**Issue by gatto** [cntrump/hugo-notepadium#38]
I was wondering if we could have a link on every page that links to the page as written in other languages.

I'm slowly learning Hugo, I know I have to create a layout for this or a partial but I don't know where to put it. I found this code:

```
{{- if .IsTranslated -}}
  <nav class="LangNav">
  {{- range .Translations -}}
    &nbsp;<a href="{{ .Permalink }}">{{- .Language.LanguageName -}}</a>
  {{ end }}
  </nav>
{{- end -}}
```

**Comment by cntrump** [comment]
Thanks, I will working on it.

**Comment by cntrump** [comment]
Updated

**Comment by gatto** [comment]
Nice. I will do my first ever pull request for this because I think I figured out an alternative. See if you like it.

**Comment by gatto** [comment]
#39
