### ISSUE TITLE
What is this line in robots.txt for?

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#4]
```
User-agent: *
Disallow:   <-- Why is this line here?
Disallow: /css/
Disallow: /js/
```

If I understand how robots.txt correctly, this line is not necessary since "Everything not explicitly disallowed is considered fair game to retrieve."

**Comment by cntrump** [comment]
It means allow **everything**, equal to `Allow: /`

See here: https://stackoverflow.com/questions/36405998/is-this-robots-txt-syntax-with-an-empty-disallow-correct

**Comment by Benjamin-Lee** [comment]
Got it, thanks for explaining.

**Comment by cntrump** [comment]
I should disallow `/css` `/js` but not `/css/` `/js/`

`robots.txt` updated.
