### ISSUE TITLE
[Feature Request] Compact Tag list

### ISSUE THREAD

**Issue by MarcusE1W** [cntrump/hugo-notepadium#41]
Hi. 

Thanks for this great theme. I am really enjoying it.

It turns out I might be using the Tag function a bit excessively and now ended up with three pages on the Tag list. Given that each tag line need quite a lot of space, is there a way to show this more compact? Maybe all tags one by one comma separated like so:

> Linux, OS, Ocaml, Keyboard 

Same like the original list, just more compact formatting?

**Comment by cntrump** [comment]
Create an user-side partial: `article-labels.html`

```
./layouts/partials/article-labels.html
```

```html
{{- if or .Params.categories .Params.tags -}}
<section class="article labels">
    {{- range $i, $e := .Params.categories -}}
        {{- if $i -}}<span>, </span>{{- end -}}
        {{- $url := print "/categories/" ($e | urlize) "/" -}}
        <a href={{- $url | relLangURL -}}>{{- $e -}}</a>
    {{- end -}}
    {{- range $i, $e := .Params.tags -}}
        {{- if $i -}}<span>, </span>{{- end -}}
        {{- $url := print "/tags/" ( . | urlize) "/" -}}
        <a href={{- $url | relLangURL -}}>{{- . -}}</a>
    {{- end -}}
</section>
{{- end -}}
```

**Comment by MarcusE1W** [comment]
Thanks. I’ll try that 😀

**Comment by MarcusE1W** [comment]
Hi. I have copied the file in the suggested folder but the Tags list seems to look exactly the same. I am probably missing something >

**Comment by MarcusE1W** [comment]
Ok, I made mild progress, copying notes-list.html and deleting the line:
```
<p class="note date">{{- .Date.Format $dateFormat -}}</p>
```
got me rif of the date in the Tag list, but its still a list with one tag per line. I will experiment more.

**Comment by cntrump** [comment]
I added `note-labels.html` partial for note list.

Now you can create an user-side partial overrite it:

```html
{{- if or .Params.categories .Params.tags -}}
    <p class="note labels">
        {{- range $i, $e := .Params.categories -}}
            {{- if $i -}}<span>, </span>{{- end -}}
            {{- $url := print "/categories/" ($e | urlize) "/" -}}
            <a href="{{- $url | relLangURL -}}">{{- $e -}}</a>
        {{- end -}}
        {{- range $i, $e := .Params.tags -}}
            {{- if $i -}}<span>, </span>{{- end -}}
            {{- $url := print "/tags/" ($e | urlize) "/" -}}
            <a href="{{- $url | relLangURL -}}">{{- $e -}}</a>
        {{- end -}}
    </p>
{{- end -}}
```

Try it ~
