### ISSUE TITLE
[Enhancement] Mermaid

### ISSUE THREAD

**Issue by MarcusE1W** [cntrump/hugo-notepadium#42]
Hugo Version:  0.62

Hi.
I have found a really easy way to use  Mermaid with this theme to draw flowcharts, maybe this can be included in the theme or just in the docu?

https://absolute-beginner.netlify.com/post/mermaid/

**Comment by cntrump** [comment]
Thanks!
I updated and you can add mermaid supporting:

1. Create an user-side partial: `./layouts/partials/js.html`

    ```html
    {{- if eq .Params.mermaid true -}}
    <!-- MermaidJS support -->
    <script async src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
    {{- end -}}
    ```

2. Create an user-side shortcode: `./layouts/shortcodes/mermaid.html`

    ```html
    <!-- MermaidJS support -->
    <div class="mermaid">
    {{- .Inner -}}
    </div>
    ```
