### ISSUE TITLE
Page Specific Custom JavaScript 

### ISSUE THREAD

**Issue by cmpadden** [cntrump/hugo-notepadium#43]
Hugo Version:  _Hugo Static Site Generator v0.64.1/extended darwin/amd64 BuildDate: unknown_

I have a custom JavaScript file that I want to run on a specific page. I added the following configuration to the front-matter of my post:

```
assets:
  js:
    - "js/example.js"
```

However, the `custom-js.html` partial is looking at the global site parameters to find the custom JS:

```
{{- range site.Params.assets.js -}}
```

To get the page-specific JavaScript to work, I had to change that line to the following:

```
{{- range $.Param "assets.js" -}}
```

Is this the optimal way of doing this, or is there a better approach?

~Thanks

**Comment by cntrump** [comment]
config.toml is global settings.
You should create an user-side shortcode ?

**Comment by cmpadden** [comment]
Yes, that may be a more robust solution -- thank you.

Though, it may be a limitation that the shortcode content is rendered in the middle of the document, whereas the parameterized partial is rendered at the bottom of the document.

**Comment by cntrump** [comment]
Another way:
https://github.com/cntrump/hugo-notepadium/issues/42#issuecomment-578563793

**Comment by cmpadden** [comment]
I like that solution the most! Thanks for your help.
