### ISSUE TITLE
Cannot add site logo

### ISSUE THREAD

**Issue by yudapedia** [cntrump/hugo-notepadium#46]
Hugo Version:  0.64

I have changed `config.toml` file by modifying `logo = "/img/logo.png"`
I also uploaded `logo.png` to '/img/' folder. The image was 512 px to 512 px.
After rebuilding my site, the logo did not show. It only show blank square.

**Comment by cntrump** [comment]
try `/static/img/logo.png`

**Comment by yudapedia** [comment]
It works by moving the logo to `/static/img/logo.png`!
Using `logo = "img/logo.png"` also works.

Thank you.
