### ISSUE TITLE
Category页面为空

### ISSUE THREAD

**Issue by fastzhong** [cntrump/hugo-notepadium#50]
Hugo Version:  Hugo Static Site Generator v0.66.0/extended darwin/amd64 BuildDate: unknown
Build Command: hugo

非得用这种格式：
```
+++
...
categories = ["abc"]
...
+++

```
默认的这种产生不出categories（空的category页面）
```
---
...
categories: ["abc"]
...
---
```

**Comment by cntrump** [comment]
> categories

参考这里 https://gohugo.io/content-management/front-matter/

你的写法有误
