### ISSUE TITLE
404能不能也改成同样的式样

### ISSUE THREAD

**Issue by fastzhong** [cntrump/hugo-notepadium#51]
Hugo Version:  Hugo Static Site Generator v0.66.0/extended darwin/amd64 BuildDate: unknown
Build Command: hugo server

404 page not found

**Comment by cntrump** [comment]
已经内置有一个 404 页面了，本地环境查看 404 页面：http://localhost:1313/404.html
如果部署到其他平台，需要按平台规则设置 404 页面，参考官方文档：https://gohugo.io/templates/404/

**Comment by cntrump** [comment]
是指把 404 调整成和其他页面一样的样式吗？
