### ISSUE TITLE
摘要部分能不能控制

### ISSUE THREAD

**Issue by fastzhong** [cntrump/hugo-notepadium#52]
Hugo Version:  Hugo Static Site Generator v0.66.0/extended darwin/amd64 BuildDate: unknown
Build Command: hugo

有些摘要太长，或者中间截一半，最好能自己控制。

**Comment by fastzhong** [comment]
\<!--more--\> 自己解决啦

**Comment by cntrump** [comment]
官方文档有介绍几种控制的方法：https://gohugo.io/content-management/summaries/
