### ISSUE TITLE
Nav标签翻译问题

### ISSUE THREAD

**Issue by Huelse** [cntrump/hugo-notepadium#53]
Hugo Version:  0.65.3
Build Command: hugo -D
在config.toml配置了`defaultContentLanguage = "zh-CN"`
确保了生成的静态页中`<html lang="zh-CN">`
但主题目录下只有`i18n/zh.toml`，此时静态页的Nav标签不会显示字，也就看不见了
只有手动改这个文件名为`zh-CN.toml`或者配置`defaultContentLanguage = "zh"`
希望这一小点改进下

**Comment by cntrump** [comment]
> Hugo Version: 0.65.3
> Build Command: hugo -D
> 在config.toml配置了`defaultContentLanguage = "zh-CN"`
> 确保了生成的静态页中`<html lang="zh-CN">`
> 但主题目录下只有`i18n/zh.toml`，此时静态页的Nav标签不会显示字，也就看不见了
> 只有手动改这个文件名为`zh-CN.toml`或者配置`defaultContentLanguage = "zh"`
> 希望这一小点改进下

hugo 的多语言是需要对应上才能读取字符串，如果没有就会显示空字符串，这个是 hugo 的特性。
只能自己做调整了。

https://github.com/cntrump/hugo-notepadium/issues/40#issuecomment-584514251

**Comment by cntrump** [comment]
之前想过用 zh-CN 还是 zh ，保证最老的兼容性，就选了 zh 。
btw： zh-CN 也不是标准写法。
参考这个：https://www.zhihu.com/question/20797118
直接就用 zh 算了。。
