### ISSUE TITLE
cant build properly

### ISSUE THREAD

**Issue by InvisibleRasta** [cntrump/hugo-notepadium#57]
Hugo Version:  0.68.3
Build Command: hugo
Hello, I have been trying to use your theme, I added it to my theme  folder and when i launch the server everything works perfectly... but when building it with the command hugo, i click on the public/index.html and the page is just white with text https://i.imgur.com/u5ygLRV.png

**Comment by cntrump** [comment]
Because got an error:
```log
GET file:///css/core.min.dd5205527998168e53b52fa8c89c1c62d4ab7c724ca28242df50a57a7b69e918e6465a463d96ffd00ef82c1affc0b44b.css net::ERR_FILE_NOT_FOUND
```

**Comment by cntrump** [comment]
Recommend debug theme with hugo server mode.
