### ISSUE TITLE
Tag “C#” page show 404

### ISSUE THREAD

**Issue by GhostBasenji** [cntrump/hugo-notepadium#59]
When I click on the C# tag, page 404 appears. How did I figure it out that the " # " symbol is specific. How is this resolved?

**Comment by cntrump** [comment]
https://discourse.gohugo.io/t/tag-c-page-show-404/12991
https://github.com/xianmin/hugo-theme-jane/pull/84

I added this patch

**Comment by GhostBasenji** [comment]
Yes, you fixed this bug. And it works if you click on the labels under the articles. 
But if you click in the upper corner, where the categories and tags are. Then there is still a bug.

**Comment by cntrump** [comment]
Thanks, fixed now.

```toml
[[params.nav.custom]]
title = "C#"
url = "/tags/c#/"
```

works well.

**Comment by GhostBasenji** [comment]
Excuse me. Apparently, I didn't describe the error very clearly.
If click on a category or tags, and then select a category or tag with C# from the list of categories or tags. So the 404 error is being made. 
But if you click on the tag or categories under the page, it is displayed normally.

**Comment by cntrump** [comment]
Updated, try again please.

**Comment by GhostBasenji** [comment]
Great thanks for help!
