### ISSUE TITLE
Twitter preview doesn't show when posting link

### ISSUE THREAD

**Issue by vinliao** [cntrump/hugo-notepadium#66]
Hugo Version:  0.69
Build Command: hugo

I'd like to have a preview below my link when I post a link on twitter. But with hugo-notepadium, the tweet doesn't have any preview.

Here's with preview (not notepadium)
![Screenshot from 2020-04-16 11-42-42](https://user-images.githubusercontent.com/34117807/79415377-74a6b500-7fd7-11ea-9354-d8cc5151bb22.png)

Here's without preview
![Screenshot from 2020-04-16 11-41-55](https://user-images.githubusercontent.com/34117807/79415388-7cfef000-7fd7-11ea-9bf7-8129c6fb8bea.png)

It might have something to do with the meta tags, as I search around looking for answers. But I'm not really sure.

**Comment by cntrump** [comment]
You are right, https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

**Comment by cntrump** [comment]
You can add an user-side partial: `head-extra.html`

```html
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="{{- .Title -}}" />
```

**Comment by vinliao** [comment]
The netlify clones this repository when building, to make the change in the real website (instead of only local) the theme must be updated.

Or is there something I am missing?

**Comment by cntrump** [comment]
I added `twitter-card.html` partial.

**Comment by vinliao** [comment]
It works!

![Screenshot from 2020-04-16 18-30-36](https://user-images.githubusercontent.com/34117807/79451315-8e182300-8010-11ea-94f0-d56d072d6eac.png)

Thanks @cntrump
