### ISSUE TITLE
Support for CSS override?

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#7]
Is there a straightforward way to inject CSS to override the default theme? I'm trying to change some minor details (font color and background in dark mode, for example) and don't see a way to do that short of overriding the style.html partial.

I was hoping that there would be something like this: https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

**Comment by cntrump** [comment]
I will try, working on it ...

**Comment by cntrump** [comment]
Done. Try it please.

### Custom CSS supporting

```
[params.assets]
css = ["css/font.css", "css/color.css"]
```

On user-side:

```
.
└── assets
    └── css
        ├── color.css
        └── font.css
```

`color.css` and `font.css` will be bundled into `core.css`.

**Comment by cntrump** [comment]
updated, now support css & js override

**Comment by Benjamin-Lee** [comment]
Worked great, thanks!
