### ISSUE TITLE
Error displaying the "." symbol.

### ISSUE THREAD

**Issue by GhostBasenji** [cntrump/hugo-notepadium#75]
For example, if you click on the tag".NET "or".Net Framework", displays this page:
`NOT FOUND
int main(int argc, char **argv) {
  printf("404");
  return 0;
}`

**Comment by cntrump** [comment]
I tested with latest code and it's ok, but I don't  do anything about  "."  ...

**Comment by cntrump** [comment]
tested with Hugo v0.69.0

**Comment by GhostBasenji** [comment]
> I tested with latest code and it's ok, but I don't do anything about "." ...

Yes? So I need to use a newer version. Before that, I use the old version. I'll check it, then give you an answer.

**Comment by GhostBasenji** [comment]
[Screenshot #1](https://i.postimg.cc/fWdN9vHK/1.jpg)
[Screenshot #2](https://i.postimg.cc/QxrrkWwr/2.jpg)

**Comment by cntrump** [comment]
> [Screenshot #1](https://i.postimg.cc/fWdN9vHK/1.jpg)
> [Screenshot #2](https://i.postimg.cc/QxrrkWwr/2.jpg)

It's weird,  I make a patch for this.
pull latest code and try

**Comment by cntrump** [comment]
I see,  just chrome can't handle '.' correctly.
Safari and Firefox is ok.

**Comment by GhostBasenji** [comment]
Hm... I'm sorry to disappoint you. Updated with your new release, but the error problem didn't go away.
You can check my site: https://ghostbasenji.github.io/tags/.net/

**Comment by cntrump** [comment]
It's very weird, I checkout your `ghostbasenji.github.io` repo and run http-server on localhost, no any problem.
I think it could be a bug of github, try bind a domain to github pages and retry?

**Comment by cntrump** [comment]
Or try host on netlify ?

**Comment by cntrump** [comment]
I guess: github pages looking for a file named '.net' and not found.

**Comment by GhostBasenji** [comment]
> I guess: github pages looking for a file named '.net' and not found.

I think so, too. We'll leave it that keep for now.

**Comment by GhostBasenji** [comment]
Find a solution. We need to create a .nojekyll file in the public folder. Works.
