### ISSUE TITLE
How does react set the code block?

### ISSUE THREAD

**Issue by livvjh** [cntrump/hugo-notepadium#76]
Hugo Version:  REPLACE_WITH_YOUR_HUGO_VERSION
Build Command: REPLACE_WITH_YOUR_HUGO_BUILD_CMD

Hi!
I use hljs. react language design does not apply to code block options.
Is there a way to solve this problem?

my config.toml setting

[params.syntax]
use = "hljs"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "atom-one-dark"
darkTheme = "xcode-dark"  

![스크린샷 2020-05-03 오후 5 20 06](https://user-images.githubusercontent.com/48043799/80909328-5f18e580-8d62-11ea-925e-6b6f87ab943d.png)

**Comment by cntrump** [comment]
can not highlight as js ?
try change react to js in codeblock

**Comment by livvjh** [comment]
thx!
It's starting to work for me !
