### ISSUE TITLE
Drop nav in favor of header right?

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#9]
The new header-right partial is a wonderful addition. In fact, I think it can replace the current nav, especially since it has the advantage of being displayed on every page:

![image](https://user-images.githubusercontent.com/13618205/71639356-453f8880-2c32-11ea-9bd9-871756874c1b.png)

What do you think @cntrump?

**Comment by cntrump** [comment]
Right, I will moving nav items to header right side.

**Comment by cntrump** [comment]
Done.

**Comment by cntrump** [comment]
`header-right.html` removed, replace it  with `navigation-items.html`.

**Comment by gatto** [comment]
How is that nav link displayed in red, up there in that screenshot? That's super cool.

**Comment by cntrump** [comment]
> How is that nav link displayed in red, up there in that screenshot? That's super cool.

```css
  color: #f25022;
  background-color: rgba(242, 80, 34, .05);
  border-radius: 3px;
```
