### ISSUE TITLE
Pages are displayed incorrectly.

### ISSUE THREAD

**Issue by GhostBasenji** [cntrump/hugo-notepadium#98]
Pages are displayed incorrectly.
The reason is that the paths are specified incorrectly.
For example:
https://ghostbasenji.github.io/page/2/post/sql-developer-roles-and-responsibilities/
https://ghostbasenji.github.io/tags/tags/unity/

And if so write the following address
https://ghostbasenji.github.io/post/unity-3d-part-i/
the page are displayed correctly.

How do I solve this problem?

**Comment by cntrump** [comment]
`note-list.html` modified ?

**Comment by GhostBasenji** [comment]
> `note-list.html` modified ?

No

**Comment by GhostBasenji** [comment]
All... I found the problem...
It should have been in the line baseURL ="/", not baseURL =".".
I'm sorry to have disturbed you. I am very ashamed that I made such a ridiculous mistake.
