### ISSUE TITLE
How to add "to top"?

### ISSUE THREAD

**Issue by GhostBasenji** [cntrump/hugo-notepadium#99]
I tried to add a "to top" button, but couldn't.
How do I implement this?

**Comment by cntrump** [comment]
```html
<a href="#header" target="_self">To top</a>
```

**Comment by GhostBasenji** [comment]
Thanks... But I was trying to place the button with the arrow in the lower right corner. Sorry for bother.

**Comment by GhostBasenji** [comment]
Thanks. I have already solved this issue with your help.
